name: Trigger Frontend Deployment

on:
  push:
    branches:
      - initial_template

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Frontend Deployment
      uses: actions/github-script@v6
      with:
        script: |
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          
          const response = await octokit.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'node.js.yml',
            ref: 'frontend_ssr'
          });
          console.log(response);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
